### ISSUE TITLE
Considerations for autocomplete behaviors?

### ISSUE THREAD

**Issue by Fishrock123** [bmeck/js-repl-goal#5]
Are there any additional considerations that would be useful to make for autocomplete or "tab-complete" behaviors for existing variables and object properties that are currently awkward to do in script / module mode?

**Comment by bmeck** [comment]
I don't think that would be in the parser/evaluation phase of the REPL so it probably wouldn't be part of ECMA262. Ideally V8 or w/e could expose the AST that would be produced in a loose manner like acorn's loose parser does, but without that this would probably be left to host/userland. I'm not in favor of specifying a loose parser though.
